name: Tests

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

jobs:
  buildtest:
    name: "Build & Test"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install exiftool
        run: sudo apt-get install -y exiftool

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"
      - run: npm ci
      - run: npm run test
      - run: npm run lint
      - run: npm run knip
